cal:-
write('Name of The Department:'),
read(X),
write('Employee Designation:'),
read(Y),
write('Name of The Employee:'),
read(Z),
write('Age:'),
read(A),
write('Basic Salary:'),
read(B),
write('Hra:'),
read(C),
D is B * 0.15,nl,
write('Dearness Allowance:'),
write(D),nl,
E is B + C + D,
write('gross salary '),
write(E),nl,nl,
write('Name of The Department:'),
write(X),nl,
write('Employee designation:'),
write(Y),nl,
write('Name of the Employee'),
write(Z),nl,
write('Age of The Employee'),
write(A),nl,
write('Basic Salary is: '),
write(B),nl,
write('Hra is: '),
write(C),nl,
write('Dearness Allowance is: '),
write(D),nl,
write('Gross Salary is: '),
write(E).