a:-
write('Product 1:- '),
write('Enter the product name:- '),
read(Name1),
write('Enter the product price:- '),
read(Price1),
write('Enter the products Manufacturing date:- '),
read(Dom1),
write('Product 2:- '),
write('Enter the product name:- '),
read(Name2),
write('Enter the products price:- '),
read(Price2),
write('Enter the products Manufacturing date:- '),
read(Dom2),
write('Product 3:- '),
write('Enter the product name:- '),
read(Name3),
write('Enter the products price:- '),
read(Price3),
write('Enter the products Manufacturing date:- '),
read(Dom3),
write('Product 4:- '),
write('Enter the product name:- '),
read(Name4),
write('Enter the products price:- '),
read(Price4),
write('Enter the products Manufacturing date:- '),
read(Dom4),
write('Product 5:- '),
write('Enter the product name:- '),
read(Name5),
write('Enter the products price:- '),
read(Price5),
write('Enter the products Manufacturing date:- '),
read(Dom5),
write('Product 6:- '),
write('Enter the product name:- '),
read(Name6),
write('Enter the products price:- '),
read(Price6),
write('Enter the products Manufacturing date:- '),
read(Dom6),
write('Product 7:- '),
write('Enter the product name:- '),
read(Name7),
write('Enter the products price:- '),
read(Price7),
write('Enter the products Manufacturing date:- '),
read(Dom7),
write('Product 8:- '),
write('Enter the product name:- '),
read(Name8),
write('Enter the products price:- '),
read(Price8),
write('Enter the products Manufacturing date:- '),
read(Dom8),
write('Product 9:- '),
write('Enter the product name:- '),
read(Name9),
write('Enter the products price:- '),
read(Price9),
write('Enter the products Manufacturing date:- '),
read(Dom9),
write('Product 10:- '),
write('Enter the product name:- '),
read(Name10),
write('Enter the products price:- '),
read(Price10),
write('Enter the products Manufacturing date:- '),
read(Dom10),
write([Name1,Price1,Dom1]),
write([Name2,Price2,Dom2]),
write([Name3,Price3,Dom3]),
write([Name4,Price4,Dom4]),
write([Name5,Price5,Dom5]),
write([Name6,Price6,Dom6]),
write([Name7,Price7,Dom7]),
write([Name8,Price8,Dom8]),
write([Name9,Price9,Dom9]),
write([Name10,Price10,Dom10]).
