cal:-
write('name of student '),
read(X),
write('roll number '),
read(Y),
write('name of subject 1 '),
read(H),
write('maximum marks for that subject is:'),nl,
read(P),
write('marks obtained in that  subject 1:'),
read(A),
write('name of subject 2 '),
read(I),
write('maximum marks for that subject is:'),nl,
read(Q),
write('marks obtained in that  subject 2:'),
read(B),
write('name of subject 3 '),
read(J),
write('maximum marks for that subject is:'),nl,
read(R),
write('marks obtained in that  subject 3:'),
read(C),
write('name of subject 4 '),
read(K),
write('maximum marks for that subject 4 is:'),nl,
read(S),
write('marks obtained in that  subject 4:'),nl,
read(D),
write('name of subject 5 '),
read(L),
write('maximum marks for that subject 5 is:'),nl,
read(T),
write('marks obtained in that  subject 5:'),nl,
read(E),
write('name of subject 6 '),
read(M),
write('maximum marks for that subject 6 is:'),nl,
read(U),
write('marks in subject 6 '),
read(F),nl,
write('name is :'),
write(X),nl,
write('roll number is :'),
write(Y),nl,
write('subject 1 is :'),
write(H),nl,
write('marks for subject 1 are '),
write(A),write('max marks are:'),write(P),nl,
write('subject 2 is :'),
write(I),nl,
write('marks for subject 2 are '),
write(B),write('max marks are:'),write(Q),nl,
write('subject 3 is :'),
write(J),nl,
write('marks for subject 3 are '),
write(C),write('max marks are:'),write(R),nl,
write('subject 4 is :'),
write(K),nl,
write('marks for subject 4 are '),
write(D),write('max marks are:'),write(S),nl,
write('subject 5 is :'),
write(L),nl,
write('marks for subject 5 are '),
write(E),write('max marks are:'),write(T),nl,
write('subject 6 is :'),
write(M),nl,
write('marks for subject 6 are '),
write(F),write('max marks are:'),write(U),nl,nl,
W is (P+Q+R+S+T+U),
G is (A+B+C+D+E+F)*100/W,nl,
write('per is '),
write(G),write('%').